apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T09:13:45Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1958"
  uid: b9afe8a5-c4cd-42cf-af38-ce98cfbedcd4
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.51.130
  clusterIPs:
  - 10.111.51.130
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31856
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
