apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T08:24:16Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "499"
  uid: 36460a44-01d7-4570-a545-1d7b42fde882
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.130.215
  clusterIPs:
  - 10.111.130.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31780
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
